#define HOME_ROW_MODS_ENABLE
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE
#define UNICODE_KEY_WINC KC_F13

#ifdef HOME_ROW_MODS_ENABLE
    #define TAPPING_TERM 200
    #define QUICK_TAP_TERM_PER_KEY
#endif
